version: '3'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - .env:/app/.env
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
    restart: always
