[build-system]
requires = ["setuptools>=42", "wheel", "bumpver", "black"]
build-backend = "setuptools.build_meta"

[project]
version = "1.0.0"
dependencies = [
    "blinker==1.9.0",
    "click==8.1.8",
    "dnspython==2.7.0",
    "dotenv==0.9.9",
    "email_validator==2.2.0",
    "Flask==3.1.2",
    "Flask-Login==0.6.3",
    "Flask-SQLAlchemy==3.1.1",
    "idna==3.10",
    "itsdangerous==2.2.0",
    "Jinja2==3.1.6",
    "markdown-it-py==4.0.0",
    "MarkupSafe==3.0.2",
    "mdurl==0.1.2",
    "Pygments==2.19.2",
    "python-dotenv==1.1.0",
    "rich==14.1.0",
    "shellingham==1.5.4",
    "SQLAlchemy==2.0.43",
    "typer==0.19.2",
    "typing_extensions==4.15.0",
    "waitress==3.0.2",
    "Werkzeug==3.1.3",
]
requires-python = ">=3.8"
authors = [
    {name = "Erik Duvander", email = "duvander@kth.se"},
    {name = "Allan Efendic", email = "allane@kth.se"},
    {name = "André Nilsson", email = "andren4@kth.se"},
]

[tool.bumpver]
current_version = "1.0.0"
version_pattern = "MAJOR.MINOR.PATCH"

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"backend/__init__.py" = ['__version__ = "{version}"']

[tool.black]
line-length = 120
